name: Frontend

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      working-directory: frontend
      run: npm ci

    - name: Lint with eslint
      working-directory: frontend
      run: npm run lint
